### ISSUE TITLE
Unable to pass image.repository through settings map

### ISSUE THREAD

**Issue by ah0lland** [DNXLabs/terraform-aws-eks-lb-controller#10]
### Contact Details (optional)

andrewxholland@gmail.com

### Description. What happened?

Hello, I'm trying to deploy the load balancer controller to my EKS instance in govcloud. I've attempted passing the appropriate repository to the helm chart via the 'settings' portion of the module but when it tries to pull the image it always uses the default repo from the eks helm chart. Any idea what I may be doing wrong?

### Steps to reproduce

I have attempted to pull the image from the us-gov-west-1 repo by configuring the module as follows

```
module "load_balancer_controller" {
  source = "git::https://github.com/DNXLabs/terraform-aws-eks-lb-controller.git"

  arn_format = "aws-us-gov"
  cluster_identity_oidc_issuer     = module.eks.cluster_oidc_issuer_url
  cluster_identity_oidc_issuer_arn = aws_iam_openid_connect_provider.eks_oidc.arn
  cluster_name                     = module.eks.cluster_id
  settings = {"image.repository":"013241004608.dkr.ecr.us-gov-west-1.amazonaws.com/amazon/aws-load-balancer-controller"}
```

```
module "load_balancer_controller" {
  source = "git::https://github.com/DNXLabs/terraform-aws-eks-lb-controller.git"

  arn_format = "aws-us-gov"
  cluster_identity_oidc_issuer     = module.eks.cluster_oidc_issuer_url
  cluster_identity_oidc_issuer_arn = aws_iam_openid_connect_provider.eks_oidc.arn
  cluster_name                     = module.eks.cluster_id
  settings = {
    "image.repository" = "013241004608.dkr.ecr.us-gov-west-1.amazonaws.com/amazon/aws-load-balancer-controller"
  }
```

### Expected behavior

I am expecting kubernetes to pull from the govcloud repo but it continues to use the default us-west-2 repo

`Normal   Pulling    51s (x3 over 88s)  kubelet            Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.2.0"`

### Actual behavior

My govcloud credentials do not work for the us-west-2 repo so the image pull fails 

`Warning  Failed     51s (x3 over 88s)  kubelet            Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.2.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-load-balancer-controller/manifests/v2.2.0: no basic auth credentials`

### Occurrence

Frequently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arthurbdiniz** [comment]
Hey @ah0lland,

Can you try breaking the settings object? 

#### Example
```
module "load_balancer_controller" {
  source = "git::https://github.com/DNXLabs/terraform-aws-eks-lb-controller.git"

  arn_format = "aws-us-gov"
  cluster_identity_oidc_issuer     = module.eks.cluster_oidc_issuer_url
  cluster_identity_oidc_issuer_arn = aws_iam_openid_connect_provider.eks_oidc.arn
  cluster_name                     = module.eks.cluster_id
  settings = {
    "image" = {
      "repository" = "013241004608.dkr.ecr.us-gov-west-1.amazonaws.com/amazon/aws-load-balancer-controller"
    }
  }
}

**Comment by ah0lland** [comment]
@arthurbdiniz That worked, thanks for your help!
