### ISSUE TITLE
"Error: Null value found in list" during `terraform plan` w/ terraform 1.0.7+

### ISSUE THREAD

**Issue by kevin-hanselman** [DNXLabs/terraform-aws-eks-lb-controller#11]
### Description. What happened?

```
$ terraform version
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.3
+ provider registry.terraform.io/hashicorp/aws v3.60.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.5.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

I also had this same problem with terraform 1.0.7.

```
$ terraform plan
...
╷
│ Error: Null value found in list
│
│   with module.load_balancer_controller.data.aws_iam_policy_document.lb_controller_assume[0],
│   on .terraform/modules/load_balancer_controller/iam.tf line 322, in data "aws_iam_policy_document" "lb_controller_assume":
│  322:     principals {
│
│ Null values are not allowed for this attribute value.
╵
```

### Steps to reproduce

I'm using the exact example code from the README:

``` hcl
module "load_balancer_controller" {
  source = "git::https://github.com/DNXLabs/terraform-aws-eks-lb-controller.git"

  cluster_identity_oidc_issuer     = module.eks_cluster.cluster_oidc_issuer_url
  cluster_identity_oidc_issuer_arn = module.eks_cluster.oidc_provider_arn
  cluster_name                     = module.eks_cluster.cluster_id
}
```

I've also tried:

```
source = "DNXLabs/eks-lb-controller/aws"
version = "0.4.1"
```

### Expected behavior

`terraform plan` succeeds.

### Actual behavior

```
$ terraform plan
...
╷
│ Error: Null value found in list
│
│   with module.load_balancer_controller.data.aws_iam_policy_document.lb_controller_assume[0],
│   on .terraform/modules/load_balancer_controller/iam.tf line 322, in data "aws_iam_policy_document" "lb_controller_assume":
│  322:     principals {
│
│ Null values are not allowed for this attribute value.
╵
```

### Occurrence

Frequently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arthurbdiniz** [comment]
Hey @kevin-hanselman,

This error looks like the variable `cluster_identity_oidc_issuer_arn` inside the module is empty.

Could be a misconfiguration on your EKS cluster that is not returning the `oidc_provider_arn` when you are using `module.eks_cluster.oidc_provider_arn`.

1. Can you check that the variable input variable `enable_irsa` is set to `true` inside your EKS module definition? 
    https://github.com/terraform-aws-modules/terraform-aws-eks#input_enable_irsa
    If  `enable_irsa` is set to `false` enable it and run the terraform stack again. 
2. Can you go to the `AWS console` > `IAM` > `Identity providers`, and check if the provider was created.
   2.1 If you couldn't find the Identity provider for your EKS cluster and you are not using the default EKS module you need to enable OIDC for your EKS module setup.
    2.2 In case the provider is showing inside the AWS console get the arn and replace ` cluster_identity_oidc_issuer_arn = module.eks_cluster.oidc_provider_arn` to  `cluster_identity_oidc_issuer_arn = "<the-copied-arn-from-console>"` to test if injecting the variable manually we stop the error.
    2.3 If works passing manually, for sure there is an error inside your EKS cluster TF module that is not exporting the `cluster_identity_oidc_issuer_arn` variable.
 
Try following these steps to see if you can solve your problem.

Can you send the version of the TF EKS module you are using and all the inputs you defined?

**Comment by e-tip** [comment]
Just a comment... if the Identity provider is created in some other way you can get it by using this
```
resource "aws_iam_openid_connect_provider" "openid_connect" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.cert.certificates.0.sha1_fingerprint]
  url             = data.aws_eks_cluster.cluster.identity[0].oidc[0].issuer
}
```

**Comment by arthurbdiniz** [comment]
Awesome @kevin-hanselman,

I'm adding `enable_irsa` input and some documentation to the example. https://github.com/DNXLabs/terraform-aws-eks-lb-controller/pull/12
 
 Cheers
