### ISSUE TITLE
Missing configuration of kubectl provider

### ISSUE THREAD

**Issue by linxsys-admin** [DNXLabs/terraform-aws-eks-lb-controller#2]
Provider kubectl is not correctly initialized in this module. It uses default configuration from environment ($KUBECONFIG or ~/.kube/config).
IMO it should be initialized with terraform-provided credentials, i.e.:

<pre>
data "aws_eks_cluster" "cluster" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "cluster" {
  name = var.cluster_name
}

provider "kubectl" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
}
</pre>

**Comment by arthurbdiniz** [comment]
Hi @linxsys-admin,

In any of our terraform EKS modules we do not configure providers inside of them. We recommend initializing the provider outside the module in case there are multiples terraform EKS modules being deployed at the same time using that provider. This way they all can share the same provider.

To give an example of that I will add the `examples` folder to this repo with more information about it.

**Comment by arthurbdiniz** [comment]
Another good thing to punctuate here is that the reason that we using this **Kubectl** provider is to create the CRDs for the controller. In the next version of the chart, this provider will not be necessary anymore since the CRDs will be installed automatically with the Helm Chart v2.

https://github.com/aws/eks-charts/pull/501

**Comment by arthurbdiniz** [comment]
Basic example :
https://github.com/DNXLabs/terraform-aws-eks-lb-controller/tree/master/examples/basic

**Comment by linxsys-admin** [comment]
OK, I understand.
The problem with this approach arises, i.e. when this module is a deep dependency.
It's a bit hard to find out, what and why tries to connect incorrect cluster.
When provider is not configured explicitly, then kubectl tries to connect to current context from it's default config file.
This is very annoying.
