### ISSUE TITLE
AWS tags for IAM resources

### ISSUE THREAD

**Issue by stdmje** [DNXLabs/terraform-aws-eks-lb-controller#30]
### Summary

Could you please add a TF variable in order to specify tags for IAM AWS resources?

### Motivation

Tagging AWS resources is a must for several purposes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickyfoster** [comment]
+1 for tags. This might be helpful.

**Comment by koslowdavida** [comment]
I suspect this would help with the [AddTags issue](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1426). Currently running into this - I think the IAM policies need to be updated to reflect the [latest required IAM actions from AWS](https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json)

**Comment by romikoops** [comment]
no updates?
