### ISSUE TITLE
Overriding default role name

### ISSUE THREAD

**Issue by OfirYaron** [DNXLabs/terraform-aws-eks-lb-controller#36]
### Summary

when using the same EKS cluster name on two different regions (the way a company I work with does) the load-balancer-controller role is used by two terraform states and constantly breaks as both effect the same role.

I've forked the repo and added a PR to fix the issue, I would love a review and possibly add it to the codebase:
https://github.com/DNXLabs/terraform-aws-eks-lb-controller/pull/35

Thanks, Ofir

### Motivation

A required feature for a company I'm working with.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brunodasilvalenga** [comment]
Closing it as the PR got merged!
