### ISSUE TITLE
Use version v2.2.0 as default helm version

### ISSUE THREAD

**Issue by mosampaio** [DNXLabs/terraform-aws-eks-lb-controller#5]
Bump to the latest version (v2.2.0) would allow us to use the latest features of this helm.

Also, it seems this IAM policy would need to be added: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.0/install/iam_policy_v1_to_v2_additional.json

More info about the migration: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.0/guide/upgrade/migrate_v1_v2/

**Comment by arthurbdiniz** [comment]
https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.0/docs/install/iam_policy.json
