### ISSUE TITLE
GovCloud ARNs not taken into account 

### ISSUE THREAD

**Issue by bbcnova** [DNXLabs/terraform-aws-eks-lb-controller#7]
When using the module in a GovCloud region (us-gov-west-1 in this case), the module fails with the following error:

```
│ Error: error creating IAM policy devint-alb-ingress: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:ec2:*:*:security-group/*".
│ 	status code: 400, request id: 31d73706-7dc1-4d2b-bc68-18ec1b0b5c6e
│ 
│   with module.load_balancer_controller.aws_iam_policy.lb_controller[0],
│   on .terraform/modules/load_balancer_controller/iam.tf line 305, in resource "aws_iam_policy" "lb_controller":
│  305: resource "aws_iam_policy" "lb_controller" {
```
This is due to ARNs in GovCloud using the format ```arn:aws-us-gov:<SERVICE>:...``` instead of ```arn:aws:<SERVICE>:...```.

I was able to get around the issue by find-and-replacing ```arn:aws:``` with ```arn:aws-us-gov:``` as a hack.

**Comment by arthurbdiniz** [comment]
Hey @bbcnova. Just created a new [release 0.4.1](https://github.com/DNXLabs/terraform-aws-eks-lb-controller/releases/tag/0.4.1) for this module that you now can specify a custom ARN format.

Take a look inside the documented inputs for the variable [arn_format](https://github.com/DNXLabs/terraform-aws-eks-lb-controller#inputs)

Cheers
